---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCjK5vW8RNnTXN+/+Jf5P7PuU17egP1/pAvCvnUgV679+JkixCfiX3Nh2Yk9vvy0hnD9mjLxp4JXOKr+Yqg72DtFAyOm5ZqieXeHfjips2pHeXsIfOZBePqx8NaRP/sn/iYoivyhWjZ8T4p8iRrfkwg0SnWsgKJ9NxqQtdU0ZzKzIxdtsTsd5ti/+uL2n+Dw1b2NOVwVf/KmNkKy7W3Ei7xX6im0srif0/X/AuXmGoZqj6gwrLtd+cnaqoPqt9UK+Qr3lDXAuyTlX23vn3TXYnAivNFo0sEhqO5qGCu1mCohcRnJtX67iQ6y27tb6ny8Ztkxuw2LS7iVx/SC3OuWzZU+qYem7Dxl/v96gcJQZImRPwc33qGeVPntztZ78HGpWL/ygB/oW96Yd5UOl1mro4VjrNzt54L5dxmGiOl5bjwqCsfg5sxTyOEuQF73Io4U4JAv+Myv9RgvJ/oWG46t6wU7kyqFiGgsGGaotIMnI4d+0pQveCpAiE19dTaEDLsFWxbnDFyZajza8+fhTVomqqItXGKjCDVPbMmyvhKybFSNnvHBo5PqUfEP0nksSmDEpqYsu26SsrKgQ8hCyLzSes1opy6byg8MlJeWU6Lle9MmHNT2XAtTVUi+6417Kqzv57CZ4qZn0K+laZunqIBPwZCSJin61HzvMj9O3z20MjQgIrQvmMt/5yEhfONcOHv4wvMEqKTcS92vJnDNhZGLSx1ageIt2JGy78=
    RUSTFS_SECRET_KEY: AgCxsIKAQvqMRAyIVZ53M6LOdKzIRQ2SQQaA9JvCtmu3Ys5uQX/uASR+xIHG+2t9Ne99HM1RH8pS3iUEDGkGaqPsKyIcHzQr2tE+rKwaWaDc0qSKx1kYhHbGQVkhX++T5mSoerBjZQeXmJYuwQTqZj1L7ZG1LZQ6/Lj+fYY+42AlAn6S/08K9zn9+SJdlZgo3XFJ/xzA4ObdQ18BqTpi8u0ecqBnlzxi6XPGpModmvHRo1fYjC80KX/DlxmtinQak6pPDQhsOhMJGGakhLQlSh2aMZMP3RmAYBK7T8nqAqugWYCS6K8MzVXo44KWaYHzVMzib4stLCf7JTJgoUNXY0fmpETUroJbFxdew4EsnjrvQ+QkfPyCm5boUxmtxGDyLHezL70kWhwLh7qIFEUBTK6x2MsEo1yw11XYdkcTWCiZhUYHUEID4pSBMI0VPxjSQOQ4rK8EgP3tCZ3wFIHte273nLO5bwIi4hifynfvn0ru6vSmFiC5NvJkA0Z/GsNyz0lUzVvQKzVEqcIcVXbnlBUvUGFYcpQ8rwE69ZoOP+zrfOZkFDiuFsvnXvodBH9VnwqxChBj1pOWItg5Wq5MltA2N43709zqBVulO0/N+p36Z4i7DviR1JnHtltny6EdWvOEA3OmP8ts1b9aLDm/j5lHkayEPCL5xDc53SmhO2FZ8kTiml8tgQcVmr/wHYOL42beKT6FKcZmWtWa7IMpetIFt8/t/vMXBQzE+56rhvrm2pVntHO3o6Sw
  template:
    metadata:
      name: rustfs-credentials
      namespace: rustfs
