[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/talosconfig"
TF_CLI_ARGS_init = "-upgrade"

[tools]
hk = "1.57.0"
pkl = "0.32.1"
gitleaks = "8.30.1"
opentofu = "1.12.6"
talosctl = "1.14.0"
kubectl = "1.37.0"
helm = "4.2.4"
argocd = "3.5.2"
kubeseal = "0.39.1"
"npm:markdownlint-cli2" = "0.23.2"
