---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBlv9AHprHLXvp0Pe/RtjwB1iB9Rm8maai0eK8M1a8N4AC3X88qihWlvKPaJdfSXpXcMAhLho6Xdkr9WRYIPZ9Tjvu2CtGwO80gfAMkmMGl0IjR7gdVqwRxNMlUhord3OhQPTePw0/UtQPDTTVOUOB1XJOpegz5vTGEmKt9lAX3AP79L+QuEhyqrKSoITbCbcDxYC0Pjn5lgobqdAMeP/kGS3kL4wL3HU/bl8ATXLu+WoJcOaMzDSdbbdorRFQGNjdOYJQKU2ITWLuj3ce3KCU5203CfRP4iHg51VG/zYcXL0OP3wtwUfC7v/Zxbxqw2hmPCscYlQiqKB/pSSeu5KiFcTYDxxi1lfOgtS+rRwQA8NDVLNBC8umMj3xYW9Pj2GuKOZVxJH8aXXJOztmUwdzNUHYdYMs96MFEIJltEVhOpal8x3WYVfrdYkMCQIJxnRFly2Sbtly+0mz+isQMLiU9g/lF+AkamoBYRHqJLl6lKbtfc7ml3QJw3XnMvMa8e7WM304TwsghlGddImeWMuYPO6KJnNmfzo4ZbBv59Bq0o0HOL57wXIbgnvP4VQODwt4n7b8eSX3rxSKaMAUg30dIpwPpRj+3MEqyc/bXJpUow1DD7mkckgcwvhg8q+65ZotCMlCLJG6bFlowcxp3oEKmGAwFDYJrYAhjb+qjurX2pLp1THIPe/UthpLOy78vxg3lPKtaUOEUnKm3cYaoRmjoyqIkXxDmVJFN1ZFJD8h9rwkZ6OabJHW3Q/7GKOXeZ1k9oSbwAw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
