---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBgRK8aVSlL91Ak42YarqmI67J3r6X4+xLfvVybx1PXOQcwcPK+DBONwRNAA7c44gXcEpo67gi7rvwOz/F42VJZtGXrMj7wuScPJ51IL4/sBjF1+VXqC2DLhTUHUqyNgazf1HUM4idYVwZ2WhO468GK/mBxqZkCCm7eO9q/i+1cfVU/k8uvQ32sdq3heku3EtajB65x2MW6/FJxr/HWE+kdH2O7BHv/BnWGyU2NCIa+GzVKYFra7ZtnhZpslZ0R3Tc+q1eprIrtWcCssDWjz/66Izxt6hxKVXMnJW7l8oYWX1AmRmOFRpIFo/O6INdoHR6dn5qqXM+wpKB6oFVocuHv/ZnFf3w9JIr268cYY1SSwvPvVAXNkhM4xqobl0gtDQYMKazQsFzBAXt9bthzOnJomKcY74xl3r1n4K6e+JntGhMYtuvJDVVUro9XfzE0wC8XpfzyX6YpBi4f/EysQ7PW8jF0+mI/+H8QuVMLEVm5AMwmrDP2JhcozXSIh08DVz/g22VrI6nxRfQfvNKEmEfI8bIKX4qnQGzBVMkeS2ovMkqUUGYQodJWMk8XQio2zhlqzFBWMc97kmD5Rw9aUDff2QpWtgF7i14l/f3hT31/Q80+gKjCFggqVoUttQj9sLZYd6NavBddm2SiEtvfedXGLv+Lc/lmOlLf/EDRYcT1S5s5IJV7ek/+ks2pd3ma4eGS/oA7fsbgKyRigZH3qCUQCz7nBjlebHZ5ksOFJbRnlAXOGIolDY5QAO17yToMCDBNPkHA93U2Wn0dY7cjE5OjwJ8tsbmIz6H1xCz4N1Qm9droaynRAGTErDEGYwE/aG/PXTYeYPTJ4ffQRxD69Oos6tjRrlEGQXbSqwY4AfGiPihvPJi21Rv4If4vu26x7uwZK5K9zGwVK9/k0JnPA2GI29jWNbmQ59LcXe4IjrMBAwfv66lGkWO9FVE5M0dyZJpG6sllmfmtaKpDoHQ6nCx/Rydn0+Z3lc8z7raMepzegVg4032TMvhOe05Z5cvRIOE=
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
