apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cloudflared
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
