---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-credentials
  namespace: loki
  annotations:
    argocd.argoproj.io/sync-wave: "-75"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAnKVV6BtzoO/acwn+qHsYDNp7vMY/zXelcsUkJHN/FPV8irFNIfkKkuquJpTuRrYPmP46D91EhoSm6r3W7AG4UDdkq63U00YTj0gZpx3E4N2r4CnJ7JoXvZHUQLmgi/TutIVuQTj6eoyET11XooeEjx203Rk+mpTnv10v3/sWZFGhv6TCjy5KX9M6BTWxoqGEKjWna8iKKSzFRs00vVdWAuz/iOvewfZn9pqWh2R0w1QtRdes+lyRGVnKPLTJzFxKaM9vdfiO/oNNSMJ3eakoUB0RURMwAenPvzyavoJmNNzXMzQIJU81sAQyysYjeMwWsEM4J3NXn+6q3ST45c4rWY8hkNsfX4dADIQzwxW4Reapt8lvDAEheDrrNlNNkEZWrC0jNP2d23OK7RSk/gH6HxnlykQj48ZYV0GDjwHBgur/goM17Z2AHXjoUKuM6agAK9kwifiojynGhbOGq9xFaUa73RlGmhyg5LhWv8mtxdjFibKKG2iaMUzpsqAa/wSg/YER1u+zzD9x12g4FpX3wDVwyFVDYIy/7ExNlAmyzybqZpusY6Ohu8iGD6iIjOuc/zunlkmhKlZuwaIc35ypmRNfL18BWejfkCWMD3HmsnH+NmMcQwDoUTYJfOqnLkAklMd7JrfjuoDgjG3TD6ZoeZD7ZxAK15zDB/FuJ1WZTCF5CxiJt0O3SoDCsSCqiVtX6kKerTIfCfd3RLAM97f3UVaC5hzIcy2o=
    AWS_SECRET_ACCESS_KEY: AgAj6ClOfpFvtyW9NwV53fH1lPkiFEWEcjxmsF0QAb9JRG+oUJPKNMilhMcbnE/yLg7MLiQT6kemYvuOtBtFXRq+bBcroXc8neA2OHeRNuAXPr9y1ynOTExXoWHVIZwdj45MSpaCCvxRV1NEiiyDOEZ6/5BveJvpopO7ZBRFVv4fZDyMprFsZ269VXph6vnm7qwXGCJsdHcs5RnjdXGk1rWowJ1nD1HhtTjUJylvnxhtlBM7mi03uECVgBw+HfpOevoHtA9ZsxSvpQcwMHpsJWEB28gr6V6S36t158MON33xwzS65JqH07itEg8Km1IxB1zs6onOlB8OCJcy9wLFGB5A7lPxFyUt0efGVWFJzLaHHjpk9YI5u2BSXGYr5TgPxauK0RmbMSNyr3iggaw4DADM1PVcigS9VVLx5r+JkzF5YtHWGD+44uLfA7bXLvFgNCaExHwEX49jP2UQPBvpOv76fHoxwsp/fz8+/XbWLExVRdJqOR1QyJPI4GSRP7M1XYk1xYhyb6+BtVk1lEK9x4vO4FZXJbEVgVEqk4MQDYQGFVmBZGqm8CBCIBK3wWw3ObPvUUhsqcgm9bDJ03bLnMkkb7i+CciDSgeV7F2ixF82gwGoH85JcrNO4xVWODo3WKIrNRN/q/dPzaZPSePeJvJiHpFSe5WFDn8gMQyg/3HunGgK7bWKBPus867SLJtCoAGsfrhSTadQSTY/ghozYRH4zxawZRV+/kP+RMvyuYKJ+NEROSxoEFbo
  template:
    metadata:
      name: loki-s3-credentials
      namespace: loki
