apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kaneo-pg
  namespace: kaneo
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: kaneo
      owner: kaneo
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi
