---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgBlxuF6oB03riPnZjEI1H3Qp/HgGp1F+y2sL3pChaqz1IBTaG+pVTLmt7KpBWo1RqFdZeDEAZn8xjEVxructpMB3GPPL16eDceKRpermEC+H3a9mgJEgBLrPw1YQdCccYOkdNhXeBDgE0G53ImKW9nE81TPv4qzbBGzDBjAa2i8yo9qtWx+0ElUTx3OP46zEVFyxg1I26vy3hP0aefFJG1M9xOdxak03Mw6oficYymG4t0OrC6YwURb/+ksfoi9LqitScmq2x8vqNDnnd2HMajgR4w7cqtEyE+DXsP2PRmE/+R1U43ZOFqUE3SmFdy6/bXnr3OrM0c2GyvIczT9OUNKy64qT5rhu9477am06YEbgkQ3MopPfhbmKpeNfnAege2uRi5RyYR8J/I4F/o598mKrIpDir4CSpvvL2BouX+6lqOe2IKawZwEFa1FFcPYFTm+QApKCDaZzBMJ541+C2G0NMggAvUL1CRGUBxkI9XSiJ0cxlrO+iiBy16+TWNOuF9ZBaf8Bg5F7DwVHjQonbM86E53syHU5mZfmIv/GqtWxCOLU2gJSKJUrMYG4Ge0fiGQkzMfJ84Ef7Hb15UZq6qFfmFR218QhZZ+QgEt7p2vPjkRug3Lgrbv+Vx0OnUDeOWyEVLHuXwU8QWT+E3+kCVlCPR5B3GwUNDHnXF3uBR+FBTSw1ajXWu7zYlvFzJmwbI9IS7ZhBbqCHnAD6DXTsIcPAJrRzNqtlLS0+ZXk/3OFcOZpwp4JY5uuQnHnO8JGom/vkLfNw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
