---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-bootstrap-admin
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgA4OEjLpvbAa4ezo7ORxR+4rztEbWKITqhaWf4OBGu9sG9LAwNR86R3Z0kR8Ey8fkgOKJnPkOOXDG6lGMwdJl8Au2SPP6tY+oa+dPdXq1L//Ng3+Wsg4dMmG2uTv8ulvEz5TM4moYiF0zR5kPgCzBdPUNIzi4GhRRDEsvVvda7hvrV03Nz9rjJGiaMFkEsY3HLDJ4K2qshht8uHubX3DEnaNhixS1ICT4okOUXSa4xeCFN5O+KwWEUqJpjhSSaNRxhh7kHWFbv2yuqLs924A7x2lPEsa/i9WBgBENwb1dfZG7jgsukQS/qLN/ri/vBmJXwCJe2hvv0CLC0ePWF1LxFvoV+fh4KzA+oqc5jxRSv5Xyy8Yy9D4FSEEiqaK51yc68AWeJ9ZXcAqf64noyT+8UsFcYRKxelNEwq+BwSq2VJEeLh/YjenASGKHZOc6hC/Igi7U3g5VnHWV0BNHSxvrOdZjk9JBUw5BvN8jEo9+3z0IqnpKynACXz9l3fHVCkg7rWW8J095ceoknE24IlRIlqrv+HbXHgbBbmNiO7vcV0v+kfhfNp2PyYnGpgHg2W5Yvtq+A5B6UUjwKXOZ87+/zbabsRAsEYs1Jq/kjFeHUL0Ut79wq2dtqASWcqKy783LyhiRY2+KB/eYdnaQ4nNrK826nPkVwR8duE2ywi1NRgNyU5n0cULnIsuiGoLTXqFs/NJoDq95vIqlwnkzmabznGD2l/jQqz4hDAai47xCDQag==
    username: AgCU/+UKUzgpubbnPdiV9muOpJvramNIjnvpvTmU2O4kTXi6hYCZ53L79fKdd+h/0PjUJ7giYotb34jYhpwhyHxPEity0wDNCM5+QKNNlXVlmzlKmBRVy1w0pai3NcjtQYNdOQAvmjIHcW8nUuh6CMEn4+CNk8lk2WSOf60r4FIbOh46hGlD8rSLy/1obD9rfpfXktDYbZCtTGY9Y6xstB7S9uuba7FJj2LldMq1V8B0geuBWwc2lkWXl7wsOLyeCFhsEz5embTqsYEXwc03vhBdLP4Dufok+18tIlRFHmM/5f+lwtmuhU/Y7Ogpn9oprGHj2v98hIT9LIJX8fhDMThasNLBE/64ZoZj2YfKU28+Jp8HbWOOgKKNIu3twT3z/j0oadapMoUwaMIW2rZKCsadgxSuNmyJHNznsXbS6QOyFT/dMRHGClAHZ+Kdhw6t3BSjW83Mj58O5YGYK5behPpRxtdyAtY7bViWOGiO4jMmwmt1s3WCldpReBUFO05cPhhzUtIuiJvWwCsV9rw5aShvDwuNTILu7cUwHdfKQ1qNRcaBap/ffYjTS9Bqa8lCv7AS5hd9EgwuJV3kpYSxkbXTAX9pNax8J6wxUhti0dtmhbASc9jY6fL2iMqX38+USgLqGbS85CqSNNpiNQI0nIW/Dx1LB1TWPyneWKqQBeOa2Q8tOtmMiWooElAY2qu+fVW89gMquA==
  template:
    metadata:
      name: keycloak-bootstrap-admin
      namespace: keycloak-system
