---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-bootstrap-admin
  namespace: keycloak
spec:
  encryptedData:
    password: AgAiE1ZCTMErdcBc6GDuvTFGDrupKQk9XEagnWVw/HsC98N1+DXTajRpx4cmhEnzwdOIsV6MYtpd/PLthffNIQT76sWIyLoPVNEYLvtB4J/0DK6SYrD1oTnu5aYYJBC+hJTkeot7iW1UkrHdpX57PjdXsbDP7NxXZD86fSl1gArHSyNL6++X8QSnOvwk/nJnm22KJgYBskoGKxFFUu7/fQZ4U9qoRE+DJBO3+cj+E9lrpb3Tchx8BH7Aaf7oKloJVFBcxctMEzTGP+WQL2S5eC2r5quulWeh9dpcafTGuLfkVdERLUQIT0dc7wFzxtZkkyQDYMHGC15WigP9bvl/j+rLRBC9KO5VTueukkQmtHxcVVZI8dYIRgVSgPa9WGxaoOa6jPEljUskCDenTS4JHb8M0nIQgzNuWT40HV0ipX5e1mAZM2b310KeWM5OaPGF201zxYESwXzMvfFYXAcAt8rqnavhla2RfXm4LP+gcPFARD5CYlF3kbXt6Bl8Kf1n7fP876ILSlPykaGXMWtoRdIxWlShV3KATLlDTpkvK6y2qbRfNuOe6zs2Dsiv3FeT7R3fH6Q6zku4dpitg08PGWiPvVhzmGCdt1e84bcQfO6JDq7lttc7ac9dtt5/SBVaaA7ASCap/DiGFePvmpAWqKwlG+fsS5uix6vg8EX8AAO3pEGK3GbhQwozFoF6K0aALjJXHWTWxYc9UhIG5MneAVZH3ONmeiM2SZKNBsS14LLGfQ==
    username: AgAP3HxUZ9SjtqcWrH798XsIkxM6TKO/22Gvs+BgJlE8DlVBp/efOKfkjZ5s9OV/4Y9qarZvyz9dX6IaCjlgl1tcspoiVuH5VYQxI1etnCc358gNDk4droGYslcyOk1WcrShxgibw7x65SCyd24zHBrRjOhV50Zd6F49YpNydDpri7QppxO0Uh7NQcYherMzNwZ0CRxVJkr0uy3EinzOqZSuQ48W9+EEA7sbGfG3TGoqnwcgsIhcLORjNkXf0E+45G+P5vmbD8ezEpfpqLMChHCPJadCIXAj0mGtt2X7/tjLtkVs/2r4NgthGWFsS2vk9Ke9+SDMhxZ+0evgdoIFWSP+nb43Oovyb+Y53/+BS0AeNO9xyB2QFwOKLrckJw72AI/K8pU4ga2np1EgDjMA47K0w6HHHsx+8LkUdUjch4MOyCOQpqoRklLqLYZn6Ok9jGR3pVHlx7R/LsuyN5lJTGEJ/64HOloJ+aSc0Nwj3BP04Hqpa7uIdzCP+oaaq4SkqhdKVWge8wUCceB1WvvAx877mFnNphPWaCk8b3cLY577h+Nn8QTXymD0xT2IBXS+q+450hEa56nJW5y7Qe1YyM2e4U4IC1sx3Ro5UhA702EKefv/pVkx9ZUbu2YCjg0fIDZ3pWIiMOD4lmAcB8E7RFwliglt69M6coe5fOMhcSuemNClid+HzOeRXSXKvwnv8rqXZyne1A==
  template:
    metadata:
      name: keycloak-bootstrap-admin
      namespace: keycloak
