---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-crossplane-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    credentials: AgAb7fEAUOpuzr17OtEiWRyk4NtxxsItq98h6KEGFhM7kd4D8aUwrSpUguJAGXnsEPPUxj5anCYa9LH8BI9t1GmiqNyxxMtj8hXdZP2KUlaBTELxQuAbs7Lk1+n28lDCyQWwH2EaaQcDrSFNWc7CgO5ZaUWFTvwvjHKBCZrgieIkZ4hIgFo3R2khCL0c/6s3u/pSerAy8V6O2MLuc6tCewLPzvFeTeDiFaxN1FmookzGldRX9GaaR7CISgddVXbjUT1iOtn0NRrQb08ME4Ba6vo9ZAVoi/Xh8qeeu6BUnhs5agAs0WOuyFA/fyEevQ/p4UA5NmTof2h3cIqdA+2GFPsazKEp7ZK3wuUI/lg3OVdipV/9n/ZfNheknSBw5ZFIGyvNpaEyyk1CBZSbq60NGnczZjpVeLcfxZqgVhWt424PiUbwuxyM49tMQrTIzDx7xAX0s9jVNmzsmr1LoyY8H0tFMT9jj/7Pn4kwW/oKamaE/oZkyV7BHxEt48CYsXOZlZohVjZJHZk1L9EADOwiPL724hn3XxJUYNG67eOwux9V9hnuk8rkiANrVUFqtLCFtm5eKz3+G2kXwqAqvrLxlqo8Y2TjEVP99alvViIeLaW5ZS4M6ZyrBk0wQcTDw2zhKg/ViQ69wJgth+UrSPwgdf3hQPYoWKoTChsRqFk0HUaBzgvmEbLRZe6xQcRuq/qpWNPZ6pT9GZEvtrYEhPyQEjVgBxVd+mqEhQL7BSocXoC+xn22jc0gC/93UshEw+PmlHGT4rg0fIoi25G+E58upPTqqNjWRamOj36sN1IWZ7T1OLx6yRcU05ZGKE03UvlOrWJc/YY6zUPGAay03RuGDBjezc1wxnNFijk9mCePOfRp/6qMlx3rAUh1Q/ccahDVSpfCcAkFOL8t4AxEl384fRFSI+P/NApuRkFwlDEdWcJfn5/tLQ==
  template:
    metadata:
      name: keycloak-crossplane-credentials
      namespace: keycloak-system
