---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-crossplane-credentials
  namespace: keycloak
spec:
  encryptedData:
    credentials: AgBZuF+ORujrCtyFPbbyKkac8lrYRoZWXZ1oFSj94jdAiFUgh65vera5n8hoRCCZzGKUZ5EufOY1fzJ6K20D+TCNz8pSrI/Z0oQoTiyXrEB1HoSMIMlGARWrfwb85r2WSeUq8M80c/mL8k/eoeJnBzhIz1Wrz6tPDX58yXoDTuXo8fOuPA91pQqJbUc093RRAuXJenS4f2yNixUqxWyGn29VFTGzfuiGqVHSzC6fy17wyvWtmvWWsXoMBB9j6WEpmBoHqbYMSHYzREKen/nJy9zS23QqtH1d780vyHQRHTJBDC39zpSKKlqhr1tLgeLUeutuaUB/LLmlygXoeAlf9eydgT5GOXED1yeOScweugUXN7HpU9JZuP1uV2q3+N0vCqiJwNZPCqLtDyajztx6TEEzO3Q3YNpZ2VwLX6LzlR+GQ9kbtgjm9yBqrV+thlrmnvujqvAVbOw9h35mohuKTGVCT9W3QAOnPAGyfTUuLrbgaL0AR+I6RXYm5giFuY92DRfLJGHj/FPpJ41AeIa2uSoflyTeENMcdgbZjcmS3TeUkJX8pVtZU+bYoAKJF1w39fV/FmTfWLKMWLgnVcEKAwNEcGkyOCuif0OmrHpM5zMSgXkGIJ4IH1pPUX4LbgU3fs+tzpENY+VZ+/xnK0yw1esLkL7ZU9FccRTWtYts74HomxQwCq06vYlk8NFXQWVQd42F/2Prkmtvtbe+leFV7tPqYdS15R3iWhuFyIWeEdnNdtRjXsWbtuAzzoZk8FhapcRXscD5qFv9I8GFLRIt26NsPrQ0ExTWSdiaPBQsh9KTOVZpnsBKWs6FR9QCNrDgQNvndWotM7TpLy6MuQ==
  template:
    metadata:
      name: keycloak-crossplane-credentials
      namespace: keycloak
