---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-crossplane-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    credentials: AgApB8nX/M1n1sH8uZ6yX8wglV4SIPYYFPwulGGl5JvJdzlTUDgKMk2aA4YKbjOAY+TOYadEdWZVNvvTPdOL8B6CSQMJptsEpGbFFAGfTx7C4S7UGuaZeFJE9RuYj+dfMBLZgtalrKvqBs3dlnmnGamXWfvEvXfDpFtZ97LufrQIXsjplGo/tVrtk63BKi/W31Eq8uez5dICkpdha7LSpYWvIkk7PCH++3347uxZabCkEIWnaYiMOOlRZg1cnKpd+hun6NHQUl66DApI5ysvtxjwor6dxl32FdCHttu7yhPTO2Zt7e0BLzEcoSkhmflethnVt5+Tw/SqCTSLjiI8VTszREBKnNqOMFS+9q//pmZ4mOBDdWff/wn1jRegxc/GK/76IIeqbw9OZc6C7gV+56EHOjgsLzt96MAO2ZrLyVnPN+6VKJbw9Vl3MLxU54+x4jvqZgZtMYnidex4wjddUGj0Pna6W2T3zUTMie66LrlVlbhUo5yEjAOM4bgfe9sDLQ7ed5Pq/Ua/YHeYm3v+0umlklSyjXdFarUPMZ6Y8DvxKpHt0hka5A1vu4q1qkFiHHuhsMCObprWraODZPP40v50+p82+x9SFC1/OqK5IO52RjrPmsJ+S9fmV/k2WKhtZM5dWwdgsvJt9Qfm7Jyy/eZFyI1glx1SqxJGQ/lIS9kUWv6Iu7fEd26iMvlGfycEK2kA5nYW5Gd1gII0dUuSoiTapijjU66ouzZkHWtdoRXKQ0p9HHm0LUkUYrIA71fyUehrfuUiNGjE2pp2eryZ6GsxQt0hHMHfKqb+zs7VpLPlm/k/DeogBogX8+yZO7naayAt8s1yjeFiP4sM4g==
  template:
    metadata:
      name: keycloak-crossplane-credentials
      namespace: keycloak-system
