---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-realm-users
  namespace: keycloak-system
spec:
  encryptedData:
    KEYCLOAK_USER_PASSWORD: AgBTAcWK2wUupCzNrBAnbDD4c2is0TCKBEiVhmjOUm6hBtuxNStdsQ537EbTrv4lcDOiuGbi1JU6uu2h1q5e1FnqBJxF+6wMyqo855Fzz1YpfngJpfzV/qCmf0hGiOk8Q24jVkknX7VwAl4u9BrqNFGQbQ39Ynop9uYE7NWNiLKmOjVjpe0+PI04wGIY8phUudxjtIYjbpDbAxQ2j8xHFOL608t8rquHaOqmHDHc2bbTY3COuCzQlWb4GQhtfh4r99UokVoFJz5iIpeY59pyha99xZVWzgzCyS/TgA8qZpLnuQuidbMB8u3wlcbexYTEjbZQ3q7P8eBV3ZuBzyoTIevKn7vjEJ4N8PX4XZ4/SoM9sbFeOBs6yT6r/E99DEtwwLLl6TzVjvwK3qS4i9Tb5+olAxuvgRtTprq9TWUZX3m1vUjFf8gnmi4yNAJAPnEr3gBzG+ndfUMT6vfHSW7hHWl/WfpcLeAAqNcnGTHHG/SRVrHydA6GFNAVi5QVYL436Pm4B1jkCFB+cC7w1SxzsLeJd0Y+iYrE5PokWDlKwzHTm03UYHTHdTAyzL0WPByX9/RpfPHUNSBlWndHx3DykGuYaVskR26qo57Z75XpmnGU4RVDGj/PTdCMPnUUtR3cyHZMIUDMHS0QuBSofEhqPwrRhWXYxb+2biV9a3N79cOUYp0FcS/GINRFKvpD3l5tN1U59KiM0LIXJfrHPRPundfS+3iSRlyfbBGT749zxRg/OQ==
  template:
    metadata:
      name: keycloak-realm-users
      namespace: keycloak-system
