---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-realm-users
  namespace: keycloak-system
spec:
  encryptedData:
    KEYCLOAK_USER_PASSWORD: AgBSlmjoHlWPN28Ngho458f8tzkk7BzN0ax4ojdB+Jjn35dBWdVvRrRYatMTgVBvD5AuKtyDupII02dI7UwilKA4VnKq9wYhmD7pClAsg+jfMk5u+d1VmhwrGTWTKGK2LSNAYbb8py3zmLsaJYyS77mWZqBm6LhBIpwGuEREN2gYQHqbPZtN3SqwomvX4/ZuLOknUUD7qsdzGz500crcfU53qYlrN/mFmuSIG/RylO1cX+KcQeHCzqvJbEU1fc2xEpNcEJKkVb4hTkCeb5BYShpt4xmzsJge5USM7OdfzoCnuez4kM6JmK4RkhXMsN0OPvARj+lYnLl3Rq7w2QjL0POMGrdxdpsOhcZ61I6CQ1QgIqAxZFF7XxOdZzKgSwCcpk8H9MoLoDv0QrCKyx4QRpTe2ncGuW+/S95E8BqR/5Hr32PaweQmHC6e0EzvZTzvwbPMHmnS/MtUZ5d6vPGRorE7z4jQ7sFSflkzMNsjuBY9xGE9Tzrz9o0dUYsUKkcyhGTgsy3SjrrK97njAX+33SjlTaHWP+Txn8MHxlyBL/sC7WTg6Kidr/4ejsBWRrmyTYwQbYuq2cRfNUPY50QFGY1/+iKRI0Jo1BZjTUo4dKe0wlMmXoYv/ltbFdDwk1oD5THFRE3k10b4SugqAoDTTXUQLiT++SLNpsnS8DD25WgMPsAo19cQw93zWzrKN7PNhHn3cPYo3rdve3vILfciKVNbS8UXHTuf3wIO62nbMIA66g==
  template:
    metadata:
      name: keycloak-realm-users
      namespace: keycloak-system
