---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgADxAFHwureOGZYD0rmk3Sk6j0IyC1/MpYda8hG4EIc6YbK6saZHCf2Bh+MLIcCVuYCpDdxy5K9FmIBvPgjoLf8O84N1wBZnDQgNu1q/OBkWEPSvYtr2/qamahcos2Oha6SsSfzXGoztwBgBDseb7vsQyhl1jB92gVplqkVRIMav50Yzmvk09jZ1PcDujk7yRKWeAb0XOmpLBVrptnO+Ps5rbgLPZ+r813Cb9mcFz2IvGfs2/UWXIypK9qYFbptJuIpMrDuQRtqd+GqfaUHhE1YYs1/Oe6y+TCknsfdfCajzozrZvPTanaBaaz2Fe+RLL94Pb0eKqciOAErx6viqkYxXxBs3zHBbrULfEvjt8QfQatN1AlR9GX6c0lKtW+r2Tq4MUnA8HJCmD/P0R+11CuZN88IaApYXGRdlj09pXjtW1bl8bWuS1ikXg87KcQuBP3VYBze/CgRsxWvDZl6lPtbQ5k+pslHaCUAYauyOY2u1sGvm7ssbXGOalSKge/oDZZtyPyTsI67NPQUubakYVtfS30DcQCC1PXTUNNUFgpvH1QQE/G1ARdzN6ZRRDE1FVfTe98Sa8ymlhRcTbppIGRNZfx0XyYIX8wvj5NjaRRZs8P0YHnrBOdzSWHG8rQu3As6ycklwmDKjVB+OjMnctyRXrbzLkxW4PdNH9hB6jwB3AUSWmq++xbN1efuwcJcED0Y293fAO2T9RLbGf05v0oLHZXTw1tKeEM4xP2QNWDgM3MVlXPdIXOkhXmYI+DC/hdJtpFRZkfl1xujRyv48r7yrSWc/rSPxUvXblk+HIyDdrqMCH9YfVkO9U/ggx8QPwCxyCYU25mQ1AitBVXaDA7yEN+FxDVVb7Ry
  template:
    metadata:
      name: rustfs-aws-credentials
      namespace: crossplane-system
