# Crossplane core helm values.

image:
  repository: xpkg.crossplane.io/crossplane/crossplane
  tag: v2.2.1

resourcesCrossplane:
  requests:
    cpu: 50m
    memory: 256Mi

resourcesRBACManager:
  requests:
    cpu: 50m
    memory: 64Mi
