apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.28.2
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/k8s/apps/cnpg-operator/values.yaml
    - repoURL: https://github.com/joelmccoy/homelab-v3.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/joelmccoy/homelab-v3.git
      targetRevision: main
      path: k8s/apps/cnpg-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
