---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    webhook.github.secret: AgAdmcfhe5sv5BTBawi+Gw2neFmaWp0Gd/gYeJimc+w0yPhL0nWTgVDV6ZoZwKoxAS2U5eMZwwG4rO8GQD5lB+aF51EijN5ronHkoBnqXrt5ZM5zC8YQ+Xk1u1tX+TvXlVVL80jJivO24+Sk7TPPRqi8tn7OR9VykxE57UkvdEHUSuupH9AiV5i8PgcLDvgNt74H190RWGUkKbLpjb/eiE71KRgbNzh7zoEP1D5kbFwbLManKwEWVjhcNN2dmAvvwwbYLJmXJjDAGxgI8siW4zEVJIHwgkeem5WZfyAfZ5UKbyDDkqwk3w55HjZa5ofPcUyGf/X5SnKM5b6mlM5NWqDL1oMfskZYRAymjmJYGhJHqa6+yQs2iu38XDADwEPSl2L3/qxP0RYG09vOel7hQgQUFOZB7/KtguNoSryKD16qUaOf1w/IMdbu5MbfsICtrlZQKUmnN4XgmDYY8nru19OemIe4HhruUwNaED0bTAr9Lz6jwEg8PrPAJnhw1M2038BH8S69X3ZOWJ+xeB3LzdCBiM3sQ0jGYQYZJCnj4oqC2aLcLvSOYa84nITkoV8bMz80ebtWcNSjMs99Ovr3Rc1sQmQR65v6erGrv8CyrXmJgeXvNG6+0aMtrDZyc/Ab5j19rm+/nHHzh5bGDsxu4rbw1SDvizsLN1TCE31s7sVR9LnKk27J6TvMBJNPs70oWGbU3wcWZM1S4pwSvf0MahI3du4YeuKnq/Ei7oU7hX8g+Wa+/XPWjOTFvKA49ixhLMSVWAMn7ZcZvqNfbUV5Mz0J
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
